### ISSUE TITLE
[BE -8.1] Corrigir relação do Serviço com o Pet

### ISSUE THREAD

**Issue by devruso** [devruso/soulpet-back#59]
Não tem coluna de chave estrangeira na tabela do serviço para acessar o Pet.

**Comment by sasalopes** [comment]
Tá certo. Farei a correção

Sabrina Lopes

Em ter., 2 de mai. de 2023 09:37, Jamilson Pestana ***@***.***>
escreveu:

**Comment by devruso** [comment]
Resolvi aqui já, era rápido.
